### ISSUE TITLE
Analyze result: Array element cannot be nil

### ISSUE THREAD

**Issue by rlaferla** [u10int/URBSegmentedControl#15]
XCode "analyze" complains of API misuse (array element cannot be nil) in the method (UIImage *)selectedBackgroundImage

	NSArray *segmentGradientColors = @[(id)segmentGradientTopColor.CGColor, (id)segmentGradientBottomColor.CGColor];

**Comment by u10int** [comment]
There just needed to be a check around that block of code where it sets up the gradient colors to ensure `segmentGradientTopColor` and `segmentGradientBottomColor` aren't `nil` before accessing and adding to the array. This should be fixed in my most recent commit.
