### ISSUE TITLE
Please Update Podspec

### ISSUE THREAD

**Issue by DoctorG** [u10int/URBSegmentedControl#16]
Thanks for fantastic control!  Much Appreciated!!

**Comment by rlaferla** [comment]
Yes, the pod needs to be updated.  It's currently at 1.0.0.  Thanks for this nice widget!

**Comment by rlaferla** [comment]
When will pod be updated?

**Comment by u10int** [comment]
@rlaferla I plan on updating the spec this evening.

**Comment by rlaferla** [comment]
Thank you.  I'm not trying to be annoying.  I'm just anxious to use your nice widget!

**Comment by u10int** [comment]
I've finally gotten around to updating the podspec to the latest, which is version 1.0.3.
