### ISSUE TITLE
Unselected segment contrast

### ISSUE THREAD

**Issue by rlaferla** [u10int/URBSegmentedControl#17]
The brightness/contrast of the unselected segment icons is too faint.  How can it be made a little brighter or with more contrast?

**Comment by u10int** [comment]
You can modify the text and icon colors for specific control states. The default colors are for the `UIControlStateNormal` state, whereas when a segment is selected, the colors defined for the `UIControlStateSelected` will be used. So just modify the colors for the `UIControlStateNormal` in your implementation.

```
- (void) setTitleTextAttributes:(NSDictionary *)textAttributes forState:(UIControlState)state;
- (void)setImageColor:(UIColor *)imageColor forState:(UIControlState)state;
```
