### ISSUE TITLE
How to change the border color of a selected Segment?

### ISSUE THREAD

**Issue by hyd00** [u10int/URBSegmentedControl#24]

**Comment by u10int** [comment]
@hyd00 Changing the border color of the segments isn't directly supported with a public property on your URBSegmentedControl instance. However, you can manually adjust the color for all segments by changing the following line in URBSegmentedControl.m, line 814 (of the latest version):

```
UIColor *segmentStrokeColor = [self.imageBackgroundColor adjustBrightness:0.5];
```
