### ISSUE TITLE
question about color

### ISSUE THREAD

**Issue by lily-Wan** [u10int/URBSegmentedControl#25]
when i run this code in iphone6 or latter,the baseColor and strokeColor became white color,like this 
![2016-05-03 2 15 43](https://cloud.githubusercontent.com/assets/19162935/14975936/98553e6a-1139-11e6-8bfb-e5f9abc8dbe0.png)

How to fix it?

**Comment by u10int** [comment]
@lily-Wan I noticed you closed this issue, so I'm assuming it's no longer an issue?

**Comment by lily-Wan** [comment]
Actually ,I find out that download from github ,the color will have problem, import by cocoa pods ,the location of the text and icon will have problem ,
![2016-06-01 4 32 44](https://cloud.githubusercontent.com/assets/19162935/15703207/a7b252e6-2816-11e6-842b-8b7be09bd81a.png)
the second situation is acceptable for me
